### ISSUE TITLE
Signup Page - Non Unique ID

### ISSUE THREAD

**Issue by unnikrishnan-r** [jt0398/Worktopia#160]
![image](https://user-images.githubusercontent.com/35500594/69496225-cb331b80-0e9d-11ea-91ea-00c2dab7f49f.png)

Found 9 elements with non-unique id #noborder: 
`<input required name=​"username" type=​"text" id=​"noborder" class=​"form-control" value>​ `

**Comment by Sachin796** [comment]
Errors Fixed
