### ISSUE TITLE
Sign Up Page - No Validation

### ISSUE THREAD

**Issue by unnikrishnan-r** [jt0398/Worktopia#161]
https://drive.google.com/file/d/171880lNquSJl97ZeJ0aBDaZm-XrcF0Fj/view

Currently, there is no validation on the Signup page.
Clicking submit does not do anything...

**Expected:** Form shows an error if mandatory parameters are not entered

**Comment by Sachin796** [comment]
Basic Validation Provided to the signup page ... error modal shown if required data is not entered.
