### ISSUE TITLE
Search and Booking - Allowing duplicate bookings

### ISSUE THREAD

**Issue by unnikrishnan-r** [jt0398/Worktopia#167]
![image](https://user-images.githubusercontent.com/35500594/69496680-a2615500-0ea2-11ea-9747-0a9e45d83f32.png)

Also see video : https://drive.google.com/file/d/1kZBNH1vqNxM7XCS3qwM8_Ju2ZPjNeeVw/view

After booking that workspace, search was showing it again for exact same dates. Allowed booking as well.

**Comment by jt0398** [comment]
Fixed in PR #191
