### ISSUE TITLE
Search Page - Dates getting reset on search results

### ISSUE THREAD

**Issue by unnikrishnan-r** [jt0398/Worktopia#171]
https://drive.google.com/file/d/19Q91FHVjgepS5Vu5J2DcCen2VUCVsjO9/view

Initially searched for 12/09 - 12/10 and clicked search.
When it navigated to "Search Results", dates got reset to default dates. Search results are also impacted

**Comment by jt0398** [comment]
@unnikrishnan-r fixed in code-cleanup-fixes PR

**Comment by jt0398** [comment]
fixed it in PR #189
