### ISSUE TITLE
Add/Edit Workspace Form Validation

### ISSUE THREAD

**Issue by jt0398** [jt0398/Worktopia#91]

**Comment by unnikrishnan-r** [comment]
@jt0398  Is there anything specific that you have in mind for this?

**Comment by jt0398** [comment]
@unnikrishnan-r Check required fields. Indicate which fields are required. If all fields are required, then there should be a message informing user that. Data length check or restriction to make sure it doesn't exceed DB field space.

**Comment by unnikrishnan-r** [comment]
Defaulted Occupancy, Location, Calendar and Picture #196
